Layout/LineLength:
  Max: 100
  Exclude:
    - realize.gemspec

Metrics/BlockLength:
  IgnoredMethods:
    - let
    - it
    - describe
    - context
    - specify
    - define

Metrics/MethodLength:
  Max: 30

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Metrics/AbcSize:
  Max: 16

Metrics/ClassLength:
  Max: 125

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
